sudo: required
services:
  - docker

before_install:
  - docker build -t bohdan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bohdan/react-test npm test

after_success:
  - docker build -t bohdaninhliziian/multi-docker-client ./client
  - docker build -t bohdaninhliziian/multi-docker-nginx ./nginx
  - docker build -t bohdaninhliziian/multi-docker-server ./server
  - docker build -t bohdaninhliziian/multi-docker-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push bohdaninhliziian/multi-docker-client
  - docker push bohdaninhliziian/multi-docker-nginx
  - docker push bohdaninhliziian/multi-docker-server
  - docker push bohdaninhliziian/multi-docker-worker
